# Load plugin from the brew path
source $BREW_LOCATION/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $BREW_LOCATION/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH_CUSTOM/plugins/git-open/git-open.plugin.zsh

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

plugins=(git git-open)

# https://github.com/bhilburn/powerlevel9k#prompt-customization
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K=truncate_beginning
POWERLEVEL9K_TIME_BACKGROUND=black
POWERLEVEL9K_TIME_FOREGROUND=white
POWERLEVEL9K_TIME_FORMAT=%D{%I:%M}
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=black
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=green
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=black
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=yellow
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=white
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=black
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=black
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=blue
POWERLEVEL9K_FOLDER_ICON=
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_VCS_UNTRACKED_ICON=●
POWERLEVEL9K_VCS_UNSTAGED_ICON=±
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=↓
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=↑
POWERLEVEL9K_VCS_COMMIT_ICON=' '
#POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
#POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{blue}╭─'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{blue}╰%f '
POWERLEVEL9K_CUSTOM_OS_ICON='echo   $(whoami) '
POWERLEVEL9K_CUSTOM_OS_ICON_BACKGROUND=red
POWERLEVEL9K_CUSTOM_OS_ICON_FOREGROUND=white

ZLE_RPROMPT_INDENT=0

# One of the first things I quickly noticed using Zsh is that many of the keys and shortcuts that I was used to, coming from bash, wouldn't work at all or resulted in unexpected behaviors.
# See: https://drasite.com/blog/Pimp%20my%20terminal

unsetopt NO_BEEP
unsetopt NO_MATCH
unsetopt AUTO_CD
unsetopt BEEP
unsetopt NOMATCH
unsetopt NOTIFY
unsetopt INC_APPEND_HISTORY
unsetopt SHARE_HISTORY
unsetopt HIST_EXPIRE_DUPS_FIRST
unsetopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_FIND_NO_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_REDUCE_BLANKS
unsetopt HIST_VERIFY
unsetopt HIST_BEEP
unsetopt INTERACTIVE_COMMENTS
unsetopt MAGIC_EQUAL_SUBST

source $DOTFILES/aliases.zsh
source $DOTFILES/functions.zsh
source $DOTFILES/path.zsh

